workflows:
  ios-build:
    name: Build iOS App
    environment:
      xcode: "15.0"
      node: "18" # Updated Node.js version to 18

    scripts:
      - name: Install dependencies
        script: |
          npm install expo
          npm install --ignore-engines
          yarn config set ignore-engines true
          npx expo install

      - name: Prebuild the iOS project
        script: |
          npx expo prebuild --platform ios

      - name: Correct Podfile
        script: |
          cd ios
          # Use sed to fix the Podfile automatically if possible
          sed -i '' 's/config = use_native_modules!/use_native_modules!/' Podfile

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update

      - name: Build iOS project
        script: |
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/YourApp.xcarchive archive

      - name: Export iOS App
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/YourApp.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR/ios_build

    artifacts:
      - $CM_BUILD_DIR/ios_build/*.ipa
