workflows:
  ios-build:
    name: Build iOS App
    environment:
      xcode: "15.0"  
      node: "16"  

    scripts:
      - name: Install dependencies
        script: |
          yarn install
          npx expo install

      - name: Build iOS project
        script: |
          npx expo prebuild --platform ios
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/YourApp.xcarchive archive

      - name: Export iOS App
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/YourApp.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR/ios_build

    artifacts:
      - $CM_BUILD_DIR/ios_build/*.ipa
